# Generated by Django 5.1.7 on 2025-04-08 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_comment_user_alter_like_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
